# Generated by Django 2.1.7 on 2019-02-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190225_0106'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='price_per_item',
            new_name='deposit',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='nmb',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='nmb',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='reservation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Reservation'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Product'),
        ),
    ]
